name: nike_ecommerce
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2
  lottie: ^3.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.4
  provider: ^6.1.2
  flutter_bloc: ^9.0.0
  sqflite: ^2.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  google_fonts: ^6.2.1


flutter:
  generate: true # Add this line
  uses-material-design: true

  fonts:
    - family: iranYekan
      fonts:
        - asset: assets/fonts/IRANYekanMobileBold.ttf
        - asset: assets/fonts/IRANYekanMobileRegular.ttf
          weight: 700
  assets:
    - assets/animation/splash/nike.json
    - assets/img/nike_logo_wite.png

flutter_native_splash:
  color: "#262A35" # رنگ پس‌زمینه صفحه اسپلش
  image: assets/img/splash/splash.png # مسیر تصویر لوگو
  android: true # فعال کردن اسپلش برای اندروید
  ios: true # فعال کردن اسپلش برای iOS
  android_12:
    icon_background_color: "#262A35" # رنگ پس‌زمینه لوگو در اندروید 12
    image: assets/img/splash/splash.png # مسیر تصویر لوگو در اندروید 12

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon/icon.png" # مسیر آیکون

